import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import LoginForm from "../components/LoginForm";
import { useEffect } from "react";
import { useStore } from "../store";
import { useRouter } from "next/router";
import Admin from "../components/Admin";

const Home: NextPage = () => {
  const user = useStore((state) => state.user);
  const router = useRouter();
  return (
    <div>
      <Head>
        <title>Qarijee - Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {user === null ? <LoginForm /> : <Admin />}
    </div>
  );
};

export default Home;
